[package]
name = "arcana"
version = "0.1.0"
edition = "2021"

[dependencies]
font8x8 = "0.3"
glam = "0.22"
minifb = "0.23"
sdl2 = { version = "0.35", features = ["bundled", "static-link", "unsafe_textures"] }